version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gymfit_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/gymfit

  frontend:
    image: nginx:alpine
    container_name: gymfit_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: gymfit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymfit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Скрипты автоматически выполнятся при первом старте базы данных
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gymfit"]
      interval: 2s
      timeout: 5s
      retries: 20

volumes:
  postgres_data: